// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMoDHQK1FC6rIfAGM_DiQM_0A_tforybQ',
    appId: '1:345553930810:web:YOUR_WEB_APP_ID',
    messagingSenderId: '345553930810',
    projectId: 'akshayahub-f7a31',
    authDomain: 'akshayahub-f7a31.firebaseapp.com',
    storageBucket: 'akshayahub-f7a31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMoDHQK1FC6rIfAGM_DiQM_0A_tforybQ',
    appId: '1:345553930810:android:ed22d2f25fb20bdedfc303',
    messagingSenderId: '345553930810',
    projectId: 'akshayahub-f7a31',
    storageBucket: 'akshayahub-f7a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMoDHQK1FC6rIfAGM_DiQM_0A_tforybQ',
    appId: '1:345553930810:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '345553930810',
    projectId: 'akshayahub-f7a31',
    storageBucket: 'akshayahub-f7a31.firebasestorage.app',
    iosBundleId: 'com.example.akshayaHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMoDHQK1FC6rIfAGM_DiQM_0A_tforybQ',
    appId: '1:345553930810:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '345553930810',
    projectId: 'akshayahub-f7a31',
    storageBucket: 'akshayahub-f7a31.firebasestorage.app',
    iosBundleId: 'com.example.akshayaHub',
  );
}
